name: Deploy Doxygen

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  gen_doxygen:
    name: generate doxygen for gh-pages
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: cd to repo
      run: echo $GITHUB_WORKSPACE && cd $GITHUB_WORKSPACE
    - name: install doxygen
      run: sudo apt-get install -y doxygen graphviz
    - name: setup cmake      
      run: mkdir build_lib && cd build_lib && cmake -G "Unix Makefiles" -DBUILD_WITH_INJECTION=ON -DCREATE_DOXYGEN_TARGET=ON -DCMAKE_BUILD_TYPE=Debug ..
    - name: compile doumentation
      run: cd build_lib && echo $(make help) && make doxygen
