name: Deploy Doxygen

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  gen_doxygen:
    name: generate doxygen for gh-pages    
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
      with:
          persist-credentials: false
    - name: cd to repo
      run: echo $GITHUB_WORKSPACE && cd $GITHUB_WORKSPACE
    - name: install doxygen
      run: sudo apt-get install -y doxygen graphviz
    - name: setup cmake      
      run: mkdir build_lib && cd build_lib && cmake -G "Unix Makefiles" -DBUILD_WITH_INJECTION=ON -DCREATE_DOXYGEN_TARGET=ON -DCMAKE_BUILD_TYPE=Debug ..
    - name: compile doumentation
      run: cd build_lib && echo $(make help) && make doxygen
    - name: Deploy 
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: docs/html # The folder the action should deploy. 
    - name: debug doc
      run: |
        sudo apt-get install tree 
        echo $(tree -d -L 4)
      
